travis:
  secure:
    BINSTAR_TOKEN: JsP+ECbzAka3c93231EgIjd+Gd+oOz4QuCsmo1yWAV9pGP8AECq13D0n8+hqfYf0LXMGhPSGnl9kOxngIG2nyFJ6qzHvIagYoeQ2qwSmqk1c6aw5+CyrvMotfJ+WtVI85kfGutWDIYwGqEwR1kgLaXTg1Ksr4hTjzjhnyYTvECksqRXpXL9xHne6Z/v5CMcRv8Alw++GoivKp4Wkkez0gGkkBWOjwp2f+8y3e+QEKD2USek/GB3pBIVnteoNQhrfoXQF5EokuR4UYyo/Iu1MP4odSPa20vRFrkHeRkgHrhw/kIWlMjzVsxOIbI1rTLlIaoLfneaN/sIy16rX3rDffTyL8EmgGu5go97oeMyXPUTF/cCip9FQydv5LfNjSxKAtx/0RwqLZeN/el8Q5Ey0Urgs7D2NmuAwrxjU5m5ira29AA6WJcljbJ0DFOPaCauTJSPt6Syb4Y7Hb9HySKKDfPfXLgmL/b9uR+Y7I2VNng+kCk7P2MPS81pMS2rNn9ZuHLoU2bmHz+58dP/611w92wP8bJRvV8wTeAfcnON6K8l+LhRX57ADdePA1QKMHMmnJxo2yyZNahx2tgThvwm3NDmZ4zD4kszcV23HXAgWJvynHHsTGnQkxe16pxydDCvjBBU+JZKygCaKNPxtql8QFqqY+S8b6ZKbQIL5aJ3g9OI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
